apiVersion: v1
kind: Pod
metadata:
  name: utility-image-gpu
  labels:
    name: utility-image-gpu
  annotations:
    scheduler.alpha.kubernetes.io/tolerations: |
      [
        {
          "key": "dedicated",
          "operator": "Equal",
          "value": "gpu-task"
        }
      ]
spec:
  # Taints for nodes will differ per kubernetes cluster
  tolerations:
    - key: dedicated
      operator: Equal
      value: gpu-task
      effect: NoSchedule  
  imagePullSecrets:
        - name: us-south-wdcloud-token
  containers:
  - name: utility-image
    image: 'registry.ng.bluemix.net/wdcloud/utility-image-gpu:1513275379'
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1
